#
# Copyright (C) 2019  Consiglio Nazionale delle Ricerche
#
#     This program is free software: you can redistribute it and/or modify
#     it under the terms of the GNU Affero General Public License as
#     published by the Free Software Foundation, either version 3 of the
#     License, or (at your option) any later version.
#
#     This program is distributed in the hope that it will be useful,
#     but WITHOUT ANY WARRANTY; without even the implied warranty of
#     MERCHANTABILITY or FITNESS FOR A PARTICULAR PURPOSE.  See the
#     GNU Affero General Public License for more details.
#
#     You should have received a copy of the GNU Affero General Public License
#     along with this program.  If not, see <https://www.gnu.org/licenses/>.
#

spring:
    jpa:
        hibernate:
            ddl-auto: none
        properties:
            hibernate:
                dialect: org.hibernate.dialect.H2Dialect
                format_sql: true
        show-sql: false

    datasource:
        url: jdbc:h2:tcp://localhost:1521/db-sigla
        username: sa
        password: sa
        driverClassName: org.h2.Driver
        maxActive: 50

cnr:
    hazelcast:
        timeToLiveSeconds: 3600
