spring.profiles.active: dev,swagger

management:
    security:
        roles: ADMIN
    context-path: /management

tomcatAjp:
    protocol: AJP/1.3
    port: 8009
    enabled: false
    scheme: http

