keycloak:
    enabled: true
    realm: cnr
    auth-server-url: http://dockerwebtest02.si.cnr.it:8110/auth
    ssl-required: NONE
    resource: sigla
    public-client: false
    use-resource-role-mappings: true
    credentials:
        secret: secret

spring:
    autoconfigure:
        exclude: org.springframework.boot.autoconfigure.session.SessionAutoConfiguration
sso:
    cnr:
        user: is_cnr_user
        matricola: matricola_cnr
        livello: livello
        contesto: sigla-app
        username_cnr: username_cnr
        logout_success_url: https://apps.cnr.it

security:
    ldap:
        change.password.url: "https://utenti.cnr.it"
