keycloak:
    auth-server-url: http://dockerwebtest02.si.cnr.it:8110/auth
    realm: cnr
    resource: sigla
    ssl-required: NONE
    credentials:
        secret: secret
    public-client: true
    use-resource-role-mappings: true 
    cors: true 
    cors-max-age: 0
    principal-attribute: preferred_username 
    cors-allowed-methods: POST, PUT, DELETE, GET 
    cors-allowed-headers: X-Requested-With, Content-Type, Authorization, Origin, Accept, Access-Control-Request-Method, Access-Control-Request-Headers
