#
# Copyright (C) 2019  Consiglio Nazionale delle Ricerche
#
#     This program is free software: you can redistribute it and/or modify
#     it under the terms of the GNU Affero General Public License as
#     published by the Free Software Foundation, either version 3 of the
#     License, or (at your option) any later version.
#
#     This program is distributed in the hope that it will be useful,
#     but WITHOUT ANY WARRANTY; without even the implied warranty of
#     MERCHANTABILITY or FITNESS FOR A PARTICULAR PURPOSE.  See the
#     GNU Affero General Public License for more details.
#
#     You should have received a copy of the GNU Affero General Public License
#     along with this program.  If not, see <https://www.gnu.org/licenses/>.
#

spring:
    jpa:
        hibernate:
            ddl-auto: none
        properties:
            hibernate:
                dialect: org.hibernate.dialect.PostgreSQL94Dialect
                format_sql: true
                jdbc:
                    lob:
                        non_contextual_creation: true
        show-sql: false

    datasource:
        url: jdbc:postgresql://localhost:5432/sigladb?schema=public
        username: sigla
        password: siglapw
        driverClassName: org.postgresql.Driver
        maxActive: 50

cnr:
    hazelcast:
        timeToLiveSeconds: 3600
